name: Go Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

#    - name: Test
#      run: go test -v ./...


    - name: Build Windows HttpServer
      run: GOOS=windows GOARCH=amd64 go build -o out/httpserver-win-amd64.exe main.go

    - name: Build Windows ARM HttpServer
      run: GOOS=windows GOARCH=arm  go build -o out/httpserver-win-arm.exe main.go

#    - name: Build Linux Amd64 HttpServer
#      run: GOOS=linux GOARCH=amd64 go build -o out/httpserver-linux-amd64 main.go

#    - name: Build Linux Arm HttpServer
#      run: GOOS=linux GOARCH=arm go build -o out/httpserver-linux-arm  main.go

#    - name: Archive Linux Arm
#      uses: actions/upload-artifact@v2
#      with:
#        name: "httpserver-linux-arm"
#        path: out/*arm*

#    - name: Archive Linux Amd64
#      uses: actions/upload-artifact@v2
#      with:
#        name: "httpserver-linux-amd64"
#        path: out/*arm*
    - name: Zip the files
      run: zip -q httpserver-windows-amd64.zip out/*win*    

    - name: Archive Windows Amd64
      uses: actions/upload-artifact@v4
      with:
        name: "httpserver-windows-amd64.exe"
        path: out/*win*

    - name: Archive Windows Amd64
      uses: actions/upload-artifact@v4
      with:
        name: "httpserver-windows-amd64.zip"
        path: httpserver-windows-amd64.zip